modLoader = "javafml"
loaderVersion = "[4,)"
license = "All Rights Reserved"

[[mods]]
modId = "carryonkick_gametest"
version = "1"
displayName = "Carry On Kick GameTests"
description = '''Development-only behavior tests.'''

[[dependencies.carryonkick_gametest]]
modId = "carryonkick"
type = "required"
versionRange = "[0.1.0,)"
ordering = "AFTER"
side = "SERVER"

[[dependencies.carryonkick_gametest]]
modId = "carryon"
type = "required"
versionRange = "[2.2.6,)"
ordering = "AFTER"
side = "SERVER"
