modLoader = "javafml"
loaderVersion = "[47,)"
license = "All Rights Reserved"

[[mods]]
modId = "carryonkick_gametest"
version = "1"
displayName = "Carry On Kick GameTests"
description = "Development-only behavior tests."

[[dependencies.carryonkick_gametest]]
modId = "carryonkick"
mandatory = true
versionRange = "[0.1.0,)"
ordering = "AFTER"
side = "SERVER"

[[dependencies.carryonkick_gametest]]
modId = "carryon"
mandatory = true
versionRange = "[2.1.2.7,)"
ordering = "AFTER"
side = "SERVER"
